dict_bancos = {
    1: "BANCO DE MEXICO (BANXICO)",
    2: "BANAMEX",
    3: "BANCA SERFIN",
    6: "BANCOMEXT",
    7: "CITIBANK, S. A.",
    9: "BANOBRAS",
    12: "BBVA MEXICO",
    14: "SANTANDER",
    19: "BANJERCITO",
    21: "HSBC",
    22: "G.E. CAPITAL",
    30: "BANCO DEL BAJIO",
    32: "IXE",
    36: "INBURSA",
    37: "INTERACCIONES",
    42: "MIFEL",
    44: "SCOTIABANK",
    58: "BANREGIO",
    59: "INVEX",
    60: "BANSI",
    62: "AFIRME",
    72: "BANORTE",
    86: "BANCEN",
    101: "BANCA CREMI",
    102: "ABN AMRO BANK MEXICO",
    103: "AMERICAN EXPRESS",
    106: "BANK OF AMERICA",
    107: "BANCO DE BOSTON",
    108: "BANK OF TOKYO",
    110: "JP MORGAN",
    112: "COMERICA BANK",
    113: "BANCO VE POR MAS",
    116: "ING BANK",
    124: "DEUTSCHE BANK",
    126: "CREDIT SUIZA",
    127: "AZTECA",
    128: "AUTOFIN MEXICO, S. A.",
    129: "BARCLAYS BANK MEXICO",
    131: "BANCO FAMSA",
    132: "BMULTIVA",
    135: "NAFIN",
    137: "BANCOPPEL",
    149: "BANRURAL",
    166: "BABIEN",
    168: "HIPOTECARIA FED",
    600: "CASA DE BOLSA MONEX",
    601: "CASA DE BOLSA GBM",
    602: "MASARI CASA DE BOLSA",
    605: "VALUE CASA DE BOLSA",
    607: "CASA DE CAMBIO TIBER",
    608: "CASA DE BOLSA VECTOR",
    610: "B Y B CASA DE CAMBIO",
    611: "INTERCAM CASA DE CAMBIO",
    612: "MAJAPARA CASA DE CAMBIO",
    613: "MULTIVALORES CASA DE BOLSA",
    614: "ACCIVAL CASA DE BOLSA",
    615: "MERRIL LYNCH CASA DE BOLSA",
    616: "CASA DE BOLSA FINAMEX",
    90646: "STP",
    9999: "GASTOS DE COBRANZA"
}


dict_emisora = {
    1: "NoAplica",
    2: "NoAplica",
    3: "NoAplica",
    4: "NoAplica",
    5: "NoAplica",
    6: "REINTENTO",
    7: "REINTENTO",
    8: "REINTENTO",
    9: "623",
    10: "623",
    11: "623",
    12: "496",
    13: "496",
    14: "496",
    15: "639",
    16: "639",
    17: "7167",
    18: "7167",
    19: "6114",
    20: "6114",
    21: "7455",
    22: "7455",
    23: "6111",
    24: "6111",
    25: "7167"
}


dict_emisora_TE = {
    1: "TRADICIONAL",
    2: "CUENTA",
    3: "TARJETA",
    4: "INTERBANCARIO",
    5: "TRADICIONAL",
    6: "TRADICIONAL",
    7: "TRADICIONAL",
    8: "TRADICIONAL",
    9: "TRADICIONAL",
    10: "TRADICIONAL",
    11: "INTERBANCARIO",
    12: "TRADICIONAL",
    13: "TRADICIONAL",
    14: "INTERBANCARIO",
    15: "EN LINEA",
    16: "EN LINEA",
    17: "TRADICIONAL",
    18: "TRADICIONAL",
    19: "MATUTINO",
    20: "MATUTINO",
    21: "EN LINEA",
    22: "EN LINEA",
    23: "PARCIAL",
    24: "PARCIAL",
    25: "INTERBANCARIO"
}


dict_respuesta_banco = {
    "00": "Domiciliacion Exitosa",
    "01": "Cuenta Inexistente",
    "02": "Cuenta Bloqueada",
    "03": "Cuenta Cancelada",
    "04": "Cuenta Insuficiencia Fondos",
    "05": "Cuenta en otra divisa",
    "06": "Cuenta no pertenece al Banco Cliente Usuario",
    "07": "Transaccion Duplicada",
    "08": "Orden de no pagara a ese Emisor",
    "09": "Importe mayor al autorizado por el cliente",
    "10": "Domiciliacion dada de  baja",
    "11": "Cuenta sin autorizacion para domiciliar",
    "12": "Cliente desconoce cargo",
    "13": "Otras causas",
    "14": "Cuenta correcta en la validacion de cuentas",
    "15": "Operacion fuera de horario",
    "16": "Caracteres Invalidos",
    "17": "Dato erroneo o invalido",
    "18": "Error en proceso de Domiciliacion",
    "19": "Operacion Invalida",
    "20": "Domiciliacion Existe",
    "21": "Baja por oficina",
    "22": "Error de proceso",
    "23": "Cuenta con todas las domiciliaciones dadas de baja",
    "24": "Cuenta no admite domiciliaciones",
    "25": "Domiciliacion no realizada",
    "26": "Bajo Pago",
    "51": "Cuenta inexistente",
    "52": "Cuenta bloqueada",
    "53": "Cuenta cancelada",
    "81": "Operación recibida fuera de horario",
    "82": "Caracteres inválidos",
    "83": "Bin inválido",
    "88": "Bloqueo a todos los cargos",
    "99": "Cuenta Correcta en la validación de cuentas",
    "D090": "Inconsistencia en la Cuenta Clabe",
    "D091": "Inconsistencia en la Cuenta Clabe",
    "D092": "Inconsistencia en la Cuenta Clabe",
    "D093": "Inconsistencia en la Cuenta Clabe",
    "D094": "Inconsistencia en la Cuenta Clabe",
    "D095": "Inconsistencia en la Cuenta Clabe",
    "D096": "Inconsistencia en la Cuenta Clabe",
    "D097": "Inconsistencia en la Cuenta Clabe",
    "D098": "Inconsistencia en la Cuenta Clabe",
    "D099": "Inconsistencia en la Cuenta Clabe",
    "D100": "Inconsistencia en la Cuenta Clabe",
    "DD00001": "Cuenta con Insuficiencia de Fondos",
    "DD00019": "Cuenta con Insuficiencia de Fondos",
    "DD00020": "Reverso del cargo a solicitud del cliente",
    "DD00021": "Cuenta Inexistente",
    "DD00022": "Cuenta con Insuficiencia de Fondos",
    "DD00023": "Transacción rechazada",
    "DD00024": "No se proceso cargo",
    "DD00025": "Cuenta Bloqueada",
    "DD00026": "Cuenta Cancelada",
    "DD00027": "Transacción rechazada",
    "DD00028": "Importe mayor al autorizado por el cliente",
    "DD00029": "Transacción rechazada",
    "DD00030": "Domiciliacion no realizada",
    "DD00031": "Cuenta con Insuficiencia de Fondos",
    "DD00033": "Domiciliacion dada de baja",
    "DD00034": "Transacción rechazada",
    "DD00035": "Transacción rechazada",
    "DD00036": "ENTREGADO",
    "DD00037": "TRANSACCION RECHAZADA",
    "DD00038": "TRANSACCIÓN RECHAZADA (OGE0076)",
    "DD00039": "TRANSACCIÓN RECHAZADA (OGE0039)",
    "DD00040": "TRANSACCIÓN RECHAZADA (OGE0041)",
    "DOM1": "Domiciliacion Exitosa",
    "DOM10": "Cuenta Bloqueada",
    "DOM11": "Transacción rechazada",
    "DOM12": "Por orden del cliente: cancelación del servicio",
    "DOM13": "Por orden del cliente: no pagar a ese emisor",
    "DOM14": "Transaccion Duplicada",
    "DOM2": "Cuenta con Insuficiencia de Fondos",
    "DOM3": "Transacción rechazada",
    "DOM4": "Domiciliacion dada de baja",
    "DOM5": "Cuenta Cancelada",
    "DOM6": "Cuenta con Insuficiencia de Fondos",
    "DOM7": "Cuenta Inexistente",
    "DOM8": "Reverso del cargo a solicitud del cliente",
    "DOM9": "Importe mayor al autorizado por el cliente",
    "INC0": "Domiciliacion Exitosa",
    "INC1": "Defuncion",
    "INC10": "Convenio cerrado",
    "INC11": "Instalando",
    "INC15": "Fraude",
    "INC16": "Cuenta Bloqueada",
    "INC17": "Dejo de pagar",
    "INC18": "Pago irregular",
    "INC19": "Liquida con virtual",
    "INC2": "Baja por jubilación",
    "INC21": "Fuera de politica",
    "INC22": "Liquida con transito",
    "INC23": "Saldo menor a cuota",
    "INC3": "Baja dependencia",
    "INC4": "Licencia",
    "INC5": "Amparo",
    "INC6": "Sin liquidez",
    "INC7": "Bajo pago",
    "INC8": "Sin pago",
    "INC9": "Cuenta Cancelada",
    "DD00041": "TRANSACCIÓN RECHAZADA (OGE0076)",
    "DD00042": "TRANSACCIÓN RECHAZADA (OGE0039)",
    "DD00043": "EN",
    "30": "30" # No esta en el diccionario
}